version: "3.9"

services: 
    mysql:
        image: mysql:5.7
        environment: 
            MYSQL_DATABASE: goods-square
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
        volumes: 
            - "./database/init.d:/docker-entrypoint-initdb.d"
        ports:
            - "3306:3306"
    backend:
        build:
            context: .
        environment: 
            - "DBHOST=mysql"
            - "DBNAME=goods-square"
            - "DBUSER=MYSQL_DBUSER"
            - "DBPASSWORD=MYSQL_DBPASSWORD"